version: '3.4'

services:
  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  fooddeliveringappdomain:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: 'Rezza@123'
        ACCEPT_EULA: 'Y'
        MSSQL_PID: 'Express'